### ISSUE TITLE
Add multi fields view example

### ISSUE THREAD

**Issue by deepak2431** [airplanedev/views-examples#3]
I would like to add a form view that has multiple fields of different data types having a SQL task to insert all the values in a given  SQL database.

**Comment by joshma** [comment]
Hey @deepak2431 , does something like https://docs.airplane.dev/templates/feature-flagging-dashboard help here?

We have more templates at https://docs.airplane.dev/templates/ and https://github.com/airplanedev/templates - this repo is an outdated repo that we should have archived, apologies for the confusion.

I'm going to close this issue for now, but feel free to follow up. You can also email us at support@airplane.dev.
